server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: mypassword
    keyStoreType: PKCS12
    keyAlias: tomcat

zuul:
  ignoredServices: '*'
  routes:
    gomoku:
      path: /proxy/**
      url: https://localhost:8080/

ribbon:
  eureka:
    enabled: false
